### ISSUE TITLE
Omit symbols from .map file

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#1017]
The .sym file already includes symbol banks+addresses (over 58,000 of them). rgblink has a `-M/--no-sym-in-map` flag that omits symbols from the .map file, which would make it [less than 1,000 lines](https://pastebin.com/i2wseCJn), and potentially easier to read to see where the sections (and empty space) are, without the redundant symbols in it.

**Comment by vulcandth** [comment]
I never really saw the point of having the symbols in the map file..seemed redundant. Was there ever some benefit to it?

**Comment by mid-kid** [comment]
@vulcandth the benefit is seeing what section each symbol belongs to, which isn't apparent at all in the symfile.

I don't really care either way, current map files are easy enough to navigate by CTRL+Fing the fields you're curious about.

**Comment by vulcandth** [comment]
> @vulcandth the benefit is seeing what section each symbol belongs to, which isn't apparent at all in the symfile.
> 
> I don't really care either way, current map files are easy enough to navigate by CTRL+Fing the fields you're curious about.

Ah yeah; I've never had to open the map file to lookup what section a symbol belongs to... So i'm fine with suppressing the symbols. That information can be obtained other ways if necessary.

**Comment by vulcandth** [comment]
Since we are discussing the `.map` files; Should we also consider adding the `.map` files to the `symbols` branch?

**Comment by vulcandth** [comment]
After discussion with @mid-kid in #1077 I think we decided to not omit the symbols. This is something the downstream user can easily do if they want. Some people use them to find out what section a symbol is in, where-as others may prefer to only see the section sizes without all of the symbols. Due to this, we should just leave this as the default setting of including the symbols in the .map files. I'll leave this issue open until @Rangi42 has a chance to concur or weigh in before closing this issue since she opened the issue.
