### ISSUE TITLE
reproduce the compressor

### ISSUE THREAD

**Issue by yenatch** [pret/pokecrystal#285]
the main sticking point is the way lookbacks are detected. merely finding the most efficient ones fails to match what the compressor does. this suggests that there is some time-saving trick at play. are there any obvious hacks that other compressors have used?

it could also be focusing on other metrics, but at a glance, it does not appear to care about decompression speed

**Comment by JimB16** [comment]
If it isn't easy to reproduce the original compressor, wouldn't it be an alternative to include a more efficient compressor in this project? I mean one that produces smaller files than the original one did?

I wanted to change one of the trainer pictures and I couldn't include it because the BANK it was included to was full. I even tried it with an unchanged picture which was stil too big.

I didn't look at the compressor yet, but was it tried to program it that way?

**Comment by yenatch** [comment]
There is a new compressor now (lzcomp). It still doesn't match, but it's more efficient and much faster.

**Comment by coltongit** [comment]
Should we just use lzcomp until the compressor is faithfully reproduced?
