### ISSUE TITLE
Segmentation fault from rgbgfx

### ISSUE THREAD

**Issue by roukaour** [pret/pokecrystal#375]
I am using commit 3c8d034, with rgbds 0.3.1 and gcc 6.3.0 (the latest available on Cygwin x86) on Windows 8.1 x64.

    $ make crystal
    make -C tools/
    make[1]: Entering directory '/cygdrive/e/Desktop/pokecrystal/tools'
    cc -std=c99 -o lzcomp lzcomp.c
    cc -std=c99 -o png_dimensions png_dimensions.c
    cc -std=c99 -o scan_includes scan_includes.c
    cc -std=c99 -o palette palette.c
    cc -std=c99 -o pokemon_animation pokemon_animation.c
    cc -std=c99 -o pokemon_animation_graphics pokemon_animation_graphics.c
    cc -std=c99 -o gfx gfx.c
    cc -std=c99 -o md5 md5.c
    make[1]: Leaving directory '/cygdrive/e/Desktop/pokecrystal/tools'
    rgbasm -o wram.o wram.asm
    rgbgfx  -d1 -o gfx/unknown/011e5d.1bpp gfx/unknown/011e5d.png
    make: *** [Makefile:198: gfx/unknown/011e5d.1bpp] Segmentation fault

When I replace rgbds with the 0.2.5 release, it gives Error 127:

    $ make crystal
    make -C tools/
    rgbgfx  -d1 -o gfx/unknown/011e5d.1bpp gfx/unknown/011e5d.png
    make: *** [Makefile:204: gfx/unknown/011e5d.1bpp] Error 127

I am curious about the motivation to use C instead of Python, which is less vulnerable to this kind of error, and would have fewer compatibility issues (I've seen multiple complaints about "cc: command not found" errors from new Cygwin users). scan_includes even used to be in Python but was replaced. Is there a significant improvement to compliation speed with the C rewrite?

**Comment by PikalaxALT** [comment]
> I am curious about the motivation to use C instead of Python

Efficiency, mostly.  Python is notoriously slow and memory-intensive compared to C, so we endeavor to use C or C++ for any process that is called frequently.

**Comment by yenatch** [comment]
The speedup is significant (easily 10x over python). Also, it was a good excuse to not depend on the submodule to build.

The cc problem really has nothing to do with c. gmake defaults `${CC}` to `cc`. It can be fixed by setting CC to gcc instead, which I was hoping to avoid. I had a `cc` alias in cygwin that I didn't put there, but couldn't test whether `gcc-core` created the alias or not. Good to know that it doesn't. Will default to gcc for now.

As for rgbgfx, make an issue. For simple programs segfaults are trivially fixed. https://github.com/rednex/rgbds/issues

**Comment by roukaour** [comment]
Thank you. I had been using the pre-built win32 releases of rgbds, which worked before. After compiling it myself, it has stopped segfaulting.

I think it would be helpful for INSTALL.md to include an FAQ of common errors, including not having a C compiler installed, and using the wrong version or build of rgbds.

The C vs Python explanation makes sense, thanks.
