### ISSUE TITLE
rename map "permission" to "environment"

### ISSUE THREAD

**Issue by yenatch** [pret/pokecrystal#396]

**Comment by mid-kid** [comment]
Since no description is provided, I might as well do it here:
Right now, there's a value that defines some of the rules that are in play in a map. This value controls things such as whether you have phone reception. Right now, this is called the map's "permission".
However, it's not very clear what rules are applied when you write, for example, `INDOOR` or `CAVE`.
As such, I proposed that maybe, just maybe, it might be more clear to call it the map's "environment". While it's still not inmediately clear what rules are applied, it seems more natural to define a map's "environment" rather than a "permission".

**Comment by Asday** [comment]
Could you point us to a list of all the possible "permission"s?

**Comment by mid-kid** [comment]
@Asday https://github.com/pret/pokecrystal/blob/master/constants/map_constants.asm#L510

**Comment by Asday** [comment]
Excellent; just wanted to make sure all of them made sense as environments.

What's the `PERM_5` one? Is that unknown for now?

**Comment by yenatch** [comment]
the term permission was grandfathered from pre-disassembly hacking resources. i don't think perm_5 is used or referenced so it's not known what it was for. maybe it was just to have one that didn't have any side effects.

**Comment by roukaour** [comment]
Is this still open because it's undecided, or it's agreed to rename them but hasn't been done yet?

**Comment by mid-kid** [comment]
I'd just do it unless someone actively objects to it.
