### ISSUE TITLE
Use constants for bitfields

### ISSUE THREAD

**Issue by roukaour** [pret/pokecrystal#429]
The `bit`, `res`, and `set` instructions are frequently used with hard-coded arguments and comments explaining their meaning (or without even the comments).

**Comment by xCrystal** [comment]
@roukaour suggested this in Discord for engine flags: 

![temp](https://user-images.githubusercontent.com/3474601/34411157-3a43cc24-ebd5-11e7-9383-92dcf21317a5.png)

Clean and simple, but would mean having to use uppercase CONSTANTS for hl load assembly instructions, which I don't think it's done anywhere.

If that's a problem, here's a more verbose alternative for `constants/engine_flags.asm` that maintains the original wram labels in assembly code.

![](https://cdn.discordapp.com/attachments/318221301615558667/395899206243713033/image.png)

I didn't want to just append `_F` to make the bit constant from the ``ENGINE_`` constant, since as far as I know this is done when the relation between them is mask versus bit. In this case, the ``ENGINE_`` constant has a different meaning.

Then it was suggested that everything could be done merging `constants/engine_flags.asm` and `data/engine_flags.asm` in a single macro, and I came up with something like this:

![](https://cdn.discordapp.com/attachments/318221301615558667/395902431684460547/image.png)
but it feels like doing things in the same place that should be done separately.

**Comment by roukaour** [comment]
If the constants are declared in `data/engine_flags.asm`, would they be visible in all the files that need them? `engine_flag` declaring `dwb` data means that it can't just be `INCLUDE`d again elsewhere the way `constants.asm` is.

**Comment by Rangi42** [comment]
Engine flags have constants now, but not all bitfields do.

**Comment by Rangi42** [comment]
475 non-mobile `bit`/`set`/`res` instructions still use raw 0-7 values: <https://pastebin.com/RPk59TB6>

**Comment by mid-kid** [comment]
That pastebin is very old, can it be updated? A lot of these have been fixed by now.

**Comment by Rangi42** [comment]
I'm not maintaining a pastebin of what's left, but you can run this command:

`grep -rE --include='*.asm' --exclude-dir=mobile '^\s(bit|res|set) [0-7],'`

Currently that outputs 444 lines.

**Comment by Rangi42** [comment]
This is an open-ended principle for future code refactoring, so it's addressed [on the wiki](../wiki/Code-cleanup).
