### ISSUE TITLE
Reorganize maps/

### ISSUE THREAD

**Issue by roukaour** [pret/pokecrystal#441]
Subdirectories within `maps/` for each landmark, including `special/`, plus `unused/` for the beta maps. (Maybe?) See PR #446 .

**Comment by Rangi42** [comment]
With landmark subdirectories, "<Landmark><Purpose>House" maps can be made less redundant. E.g. instead of "maps/goldenrod_city/GoldenrodBillsHouse.asm", "maps/goldenrod_city/BillsFamilyHouse.asm" (since "BillsHouse.asm" is the one on Route 25). Or instead of "maps/route_26/Route26DayofWeekSiblingsHouse.asm", just "maps/route_26/WeekSiblingsHouse.asm". Full list: https://pastebin.com/b0KmqRUj

**Comment by Rangi42** [comment]
Both of the map reorganization PRs were closed, so this looks like an abandoned idea.
