### ISSUE TITLE
Consistent numeric constants for bitmasks

### ISSUE THREAD

**Issue by roukaour** [pret/pokecrystal#465]
Sometimes masking uses a hex constant:

```asm
.PageTilemap: ; 4e002 (13:6002)
	ld a, [wcf64]
	and $3
	dec a
	ld hl, .Jumptable
	rst JumpTable
	ret

.Jumptable: ; 4e00d (13:600d)
	dw .PinkPage
	dw .GreenPage
	dw .BluePage
```

Sometimes a binary constant:

```asm
.CheckDVs: ; 16ebc (5:6ebc)
; If Defense DVs match and the lower 3 bits of the Special DVs match,
; avoid breeding
	ld a, [wBreedMon1DVs]
	and %1111
	ld b, a
	ld a, [wBreedMon2DVs]
	and %1111
	cp b
	ret nz
	ld a, [wBreedMon1DVs + 1]
	and %111
	ld b, a
	ld a, [wBreedMon2DVs + 1]
	and %111
	cp b
	ret
; 16ed6
```

And rarely uses `(1 << N) - 1` to indicate the *N* low bits are set:

```asm
	ld hl, .daypals
	ld a, [TimeOfDayPal]
	and (1 << 2) - 1
	cp 3
	jr nz, .daytime
	ld hl, .nightpals
.daytime
```

A standard method would make this kind of operation easier to recognize. To me the `(1 << N) - 1` format looks deceptively like it's related to the *N*th bit; can the nine instances of that be replaced with the more common hex constants? (E.g. `and $3` for the above.)

**Comment by roukaour** [comment]
Sometimes a constant would be appropriate, e.g. `ENVIRONMENT_MASK` here (since the same byte stores phone call service availability):

```asm
	ld a, [wEnvironment]
	and $7
	cp INDOOR ; Hall of Fame
```

**Comment by xCrystal** [comment]
I think most masking operations would be better with a binary value than a hex value, because it directly tells you which bits are being discarded and which aren't.

I also don't like ``(1 << N) - 1``. I guess it could be macrofied (``and low N bits``?), but I still don't think it would be enough justified.

All in all, I agree that most of those should be able to be given a constant; while those that can't (probably related to a random math operation inside some algorithm), would probably be more easily readable with an argument in binary.

**Comment by roukaour** [comment]
The `maskbits` macro should be frequently useful for this. It creates a bitmask just large enough to cover the argument. E.g. if `NUM_THING` == 12, and you have some code doing `and $f`, that can be replaced by `maskbits NUM_THING`.

**Comment by Rangi42** [comment]
This is an open-ended principle for future code refactoring, so it's addressed [on the wiki](../wiki/Code-cleanup).
