### ISSUE TITLE
"lda" macro that becomes "ld a, \1" or "xor a" if \1 == 0

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#482]
Frequently `xor a` is used as a more efficient `ld a, 0`, but this means if the 0 is some significant constant it has to be mentioned in a comment. (See `grep "xor a ;"`.) An alternative:

```
lda: MACRO
if \1 == 0
    xor a
else
    ld a, \1
endc
ENDM
```

Example usage:

```
    lda ITEM_POCKET
    ld [wCurrPocket], a
```

That takes the place of `xor a ; ITEM_POCKET`. For symmetry it could be used in the nonzero cases too. Using it consistently would mean that seeing an explicit `ld a, X` means you want to preserve flags and not "optimize" it into `xor a`. It would also mean that if you add some new 0th constant it will automatically be used correctly.

**Comment by xCrystal** [comment]
I guess this has been discarded because the ``lda`` macro hides ``xor a``'s effect on the f flags, but I had already though about it and if done in a different way I don't think it's that bad of an idea as there are many ``xor a`` that legitimately only indicate a constant with value 0.

What I though about personally is a macro like ``xor_const \1`` (e.g. ``xor_const ITEM_POCKET``) that makes the build warn you (probably better than straight up fail), if ``\1`` does not equal 0. I guess there would be a problem with a few edge cases where ``xor a`` may be both used as a value 0 constant and for setting the z flag to 0 though.

**Comment by Rangi42** [comment]
`xor_const ITEM_POCKET` looks like it would turn into `xor ITEM_POCKET`. How about just `xor_a ITEM_POCKET` as a parallel to `xor a ; ITEM_POCKET`? As you say, it would fail to compile if `ITEM_POCKET` is undefined or nonzero, instead of relying on the user to search for `ITEM_POCKET` in comments before messing with constants.

**Comment by Rangi42** [comment]
Yeah, if `tailcall` wasn't agreed on, I doubt this will be either.
