### ISSUE TITLE
Document Pokégear map down scrolling bug

### ISSUE THREAD

**Issue by SatoMew** [pret/pokecrystal#504]
Here's another one for `docs/bugs_and_glitches.md`.

The Pokégear map displays Johto location names and coordinates on the Kanto layout whenever the player scrolls it down while in Kanto before they're supposed to. This leads to an underflow after map ID `$00` (SPECIAL), which the player doesn't normally see either.

It requires ACE to reproduce without direct RAM manipulation ([video](https://www.youtube.com/watch?v=r32agevxdw4)).

https://github.com/pret/pokecrystal/blob/335c2699f0b965be90c13bd3613b1df49f32af8b/engine/pokegear.asm#L664-L673

**Fix:** (courtesy of p-p-pfero from the pret Discord)

```
.down
    ld hl, wPokegearMapCursorLandmark
    ld a, [hl]
    inc e
    cp e
    jr nc, .wrap_around_down
    inc d
    ld [hl], d
.wrap_around_down
    dec [hl]
```

**Comment by Rangi42** [comment]
I'm not sure whether this counts as a bug. The problem stems from being in a location outside the landmark limits set by calling `TownMap_GetKantoLandmarkLimits`, which assumes that you can't have reached most Kanto maps before beating the Elite 4.

```asm
TownMap_GetKantoLandmarkLimits: ; 910e8
	ld a, [wStatusFlags]
	bit STATUSFLAGS_HALL_OF_FAME_F, a
	jr z, .not_hof
	ld d, ROUTE_28
	ld e, PALLET_TOWN
	ret

.not_hof
	ld d, ROUTE_28
	ld e, VICTORY_ROAD
	ret
```

IMO this could be documented as a hard-coded logic "gotcha" in the wiki: https://github.com/pret/pokecrystal/wiki/Hard-coded-logic
Since it behaves correctly in a non-memory-corrupted game, but can bite you if you make a hack and forget to modify it.

**Comment by Rangi42** [comment]
Documented: <https://github.com/pret/pokecrystal/wiki/Hard-coded-logic#landmark-limits-when-scrolling-in-the-town-map>
