### ISSUE TITLE
Aerodactyl palettes are wrong 

### ISSUE THREAD

**Issue by AyanamiRei1** [pret/pokecrystal#529]
Checking the disassembly both normal and shiny palette they're wrong comparing it to GSC it seems like the GB palette is used for the normal one and the shiny palette should be the normal one.

From the disassembly 
![wrong](https://user-images.githubusercontent.com/25233407/41752684-eda3fea4-75c0-11e8-9176-e03bb5977215.png)

From GSC
![right](https://user-images.githubusercontent.com/25233407/41752702-037c45ba-75c1-11e8-8848-2ebed15be89d.png)

**Comment by luckytyphlosion** [comment]
The disassembly produces a matching copy of the ROM, so it would be impossible for any of the disassembly information to be incorrect. Where did you find the GSC screenshots? If they weren't made yourself, they could have been made using a filter that alters the palette.

**Comment by ketsuban** [comment]
I note that your sprites are only correct for Gold - Aerodactyl's normal palette *did* get greyer in Crystal. (You can see a side-by-side comparison on Veekun and Bulbapedia.)

That just leaves the shiny palette, which is where this gets confusing. pokecrystal by default compiles to a ROM matching that of retail Pokemon Crystal - it's impossible for there to be any errors, because those would manifest as the build failing to match the hashes in roms.sha1. How did you produce the sprites you posted?

**Comment by iimarckus** [comment]
The file in the repo is correct. Emulators (and Game Boys for that matter) saturate colors in weird ways. This is how Gambatte displays shiny Aerodactyl built from pokecrystal. Notice how none of the colors, even the menu background, perfectly match your screenshot. It all depends on the emulator.

![2018-06-21-204304_160x144_scrot](https://user-images.githubusercontent.com/1767429/41755301-d587e916-7593-11e8-9a18-b6e1207260ad.png)
