### ISSUE TITLE
rename var/byte/mem script commands

### ISSUE THREAD

**Issue by yenatch** [pret/pokecrystal#540]
before | after | what it actually does
---|---|---
writebyte | setval `value` | `[wScriptVar] = value`
addvar | addval `value` | `[wScriptVar] += value`
copybytetovar | readval `address` | `[wScriptVar] = [address]`
copyvartobyte | writeval `address` | `[address] = [wScriptVar]`
loadvar | write `address`, `value` | `[address] = value`
checkcode | getvar `var` | `[wScriptVar] = [var]`
writevarcode | setvar `var` | `[var] = [wScriptVar]`
writecode | setvar `var`, `value` | `[var] = value`
vartomem | printval `buffer` | `[wStringBuffer{buffer+3}] = PrintNum([wScriptVar])`
loadmemtrainer | settrainer | `[wOtherTrainer] = [wTempTrainer]`
pokenamemem | pokename `species`, `buffer` | `[wStringBuffer{buffer+3}] = GetPokemonName(species \|\| [wScriptVar])`
itemtotext | itemname `item`, `buffer` | `[wStringBuffer{buffer+3}] = GetItemName(item \|\| [wScriptVar])`
mapnametotext | mapname `buffer` | `[wStringBuffer{buffer+3}] = GetLandmarkName()`
landmarktotext | landmarkname `landmark`, `buffer` | `[wStringBuffer{buffer+3}] = GetLandmarkName(landmark)`
trainertotext | trainername `class`, `trainer`, `buffer` | `[wStringBuffer{buffer+3}] = GetTrainerName(class, trainer)`
stringtotext | print `string`, `buffer` | `[wStringBuffer{buffer+3}] = CopyName1([wScriptBank], string)`
readcoins | printcoins `buffer` | `[wStringBuffer{buffer+3}] = PrintNum([wCoins])`
readmoney | printmoney `buffer` | `[wStringBuffer{buffer+3}] = PrintNum([wMoney])`

**Comment by mid-kid** [comment]
`setval` -> `loadval`?

`getvar` -> `readvar` and `setvar` -> `writevar` for consistency with the `val` equivalents.

`printval` -> `printnumval` or `printvalnum`. Distinguish it from `print` properly.
Or, make it generate from `print` if _NARG < 2.

Also, the last column you just wrote is really useful to have. Might want to update `docs/event_commands.md` with them.

**Comment by Rangi42** [comment]
Reminder to keep the old names in macros/legacy.asm.

This says `setval $value` would do `[wScriptVar] = $value`, but `getvar $var` would do `[wScriptVar] = [$var]`. If the names are all getting updated, can they be kept consistent? Either `setval` and `setvar` or `getval` and `getvar` should both modify `[wScriptVar]`. (Probably `set`, since conceptually it's `[wScriptVar]` that's being got/set, right?)

**Comment by mid-kid** [comment]
I'd do `write` and `read`, since you're reading a value from an address or a variable, but otherwise, yeah.

**Comment by luckytyphlosion** [comment]
`getvar` meaning the variable engine can be confused with the actual wScriptVar. I don't know a better solution though.

**Comment by Rangi42** [comment]
How about:

- `landmarktotext` → `<X>landmarkname`
- `trainertotext` → `<X>trainername`
- `stringtotext` → `<X>string`
- `readcoins` → `<X>coins`
- `readmoney` → `<X>money`

where `<X>` = `buffer` or `print`.

**Comment by luckytyphlosion** [comment]
That would imply that it's printed on the screen, which it isn't.

**Comment by Rangi42** [comment]
True, `print` would, so `buffer` then. Or at least some verb; `landmarkname` could be doing anything landmark-name-related.

**Comment by mid-kid** [comment]
What about `<x>` = `get`?

**Comment by Rangi42** [comment]
> What about `<x>` = `get`?

Not if `getfoo` is going to mean `[wScriptVar] = foo` or `foo = [wScriptVar]`.

**Comment by aaaaaa123456789** [comment]
I'd say that the mentions of `val` are completely unnecessary; it's obvious that the commands operate on the values in front of them. And we should avoid `set` and `get` when `read` and `write` are clearer.

Also, I'd try to avoid `<foo>to<bar>` names unless necessary. All those commands that operate on buffers could be replaced by a single multiplexed command: (note: all words not in angled brackets are literals)

* `pokenamemem <species>, <buffer>` → `buffertext <buffer>, species, <species>`
* `itemtotext <item>, <buffer>` → `buffertext <buffer>, item, <item>`
* `mapnametotext <buffer>` → `buffertext <buffer>, landmark, current`
* `landmarktotext <landmark>, <buffer>` → `buffertext <buffer>, landmark, <landmark>`
* `trainertotext <class>, <index>, <buffer>` → `buffertext <buffer>, trainer, <class>, <index>`
* `stringtotext <name>, <buffer>` → `buffertext <buffer>, string, <name>`
* `readcoins <buffer>` → `buffertext <buffer>, coins`
* `readmoney <buffer>` → `buffertext <buffer>, money`
* `vartomem <buffer>` → `buffertext <buffer>, scriptvar`

While this would require a multiplexing macro (not hard to implement, just different from the others), it would solve quite a bit of the name inconsistency in one go. Also, I wrote the commands destination first (just like gbz80) instead of source first, despite they are the other way around in ROM; this is just for readability.

**Comment by Rangi42** [comment]
Not a fan of multiplexed commands. Visible command names and internal command ID bytes should be one-to-one.

**Comment by Rangi42** [comment]
A revised renaming proposal, after checking the above comments. We already renamed `passtoengine` to `autoinput`, but the rest can still be improved.

| legacy | proposal | effect |
| --- | --- | --- |
| <code>writebyte <i>value</i></code> | <code>readval <i>value</i></code> | <code>[wScriptVar] = <i>value</i></code> |
| <code>addvar <i>value</i></code> | <code>addval <i>value</i></code> | <code>[wScriptVar] += <i>value</i></code> |
| <code>copybytetovar <i>address</i></code> | <code>readfrom <i>address</i></code> | <code>[wScriptVar] = [<i>address</i>]</code> |
| <code>copyvartobyte <i>address</i></code> | <code>writeto <i>address</i></code> | <code>[<i>address</i>] = [wScriptVar]</code> |
| <code>loadvar <i>address</i>, <i>value</i></code> | <code>loadto <i>address</i>, <i>value</i></code> | <code>[<i>address</i>] = <i>value</i></code> |
| <code>checkcode <i>variable</i></code> | <code>readvar <i>variable</i></code> | <code>[wScriptVar] = {<i>variable</i>}</code> |
| <code>writevarcode <i>variable</i></code> | <code>writevar <i>variable</i></code> | <code>{<i>variable</i>} = [wScriptVar]</code> |
| <code>writecode <i>variable</i>, <i>value</i></code> | <code>loadvar <i>variable</i>, <i>value</i></code> | <code>{<i>variable</i>} = [<i>value</i>]</code> |

(<code>{<i>variable</i>}</code> represents `VAR_*` access; see [engine/overworld/variables.asm](/engine/overworld/variables.asm).)

| legacy | proposal | effect |
| --- | --- | --- |
| <code>vartomem <i>memory</i></code> | <code>getnum <i>memory</i></code> | <code>{<i>memory</i>} = PrintNum([wScriptVar])</code> |
| <code>pokenamemem <i>mon_id</i>, <i>memory</i></code> | <code>getmonname <i>memory</i>, <i>mon_id</i></code> | <code>{<i>memory</i>} = GetPokemonName(<i>mon_id</i>)</code> (`USE_SCRIPT_VAR` for `[wScriptVar]`) |
| <code>itemtotext <i>item_id</i>, <i>memory</i></code> | <code>getitemname <i>memory</i>, <i>item_id</i></code> | <code>{<i>memory</i>} = GetItemName(<i>item_id</i>)</code> (`USE_SCRIPT_VAR` for `[wScriptVar]`) |
| <code>mapnametotext <i>memory</i></code> | <code>getcurlandmarkname <i>memory</i></code> | <code>{<i>memory</i>} = GetLandmarkName(GetWorldMapLocation())</code> |
| <code>landmarktotext <i>landmark_id</i>, <i>memory</i></code> | <code>getlandmarkname <i>memory</i>, <i>landmark_id</i></code> | <code>{<i>memory</i>} = GetLandmarkName(<i>landmark_id</i>)</code> |
| <code>trainertotext <i>trainer_group</i>, <i>trainer_id</i>, <i>memory</i></code> | <code>gettrainername <i>memory</i>, <i>trainer_group</i>, <i>trainer_id</i></code> | <code>{<i>memory</i>} = GetTrainerName(<i>trainer_group</i>, <i>trainer_id</i>)</code> |
| <code>stringtotext <i>text_pointer</i>, <i>memory</i></code> | <code>getstring <i>memory</i>, <i>text_pointer</i></code> | <code>{<i>memory</i>} = CopyName1([wScriptBank], <i>text_pointer</i>)</code> |
| <code>readcoins <i>memory</i></code> | <code>getcoins <i>memory</i></code> | <code>{<i>memory</i>} = PrintNum([wCoins])</code> |
| <code>readmoney <i>memory</i></code> | <code>getmoney <i>memory</i></code> | <code>{<i>memory</i>} = PrintNum([wMoney])</code> |

(<code>{<i>memory</i>}</code> represents `MEM_BUFFER_0/1/2` access to `wStringBuffer3/4/5`; see `ConvertMemToText` in [engine/overworld/scripting.asm](/engine/overworld/scripting.asm).)

I moved the <code><i>memory</i></code> arguments first to match the standard loading-command pattern of "destination, source".

Instead of `get`, the common prefix could be `buffer`, or `print` (although `print` might imply printing directly to the screen).

| legacy | proposal | effect | notes |
| --- | --- | --- |
| <code>loadmemtrainer</code> | <code>loadtemptrainer</code> | <code>[wOtherTrainer] = [wTempTrainer]</code> | only used by [engine/events/trainer_scripts.asm](/engine/events/trainer_scripts.asm) |
| <code>changemap <i>bank</i>, <i>blockdata_pointer</i></code> | <code>changemapblocks <i>dba_blockdata_pointer</i></code> | <code>ChangeMap([<i>dba_blockdata_pointer</i>])</code> | unused |

I'll keep this comment up-to-date with revisions.

**Comment by aaaaaa123456789** [comment]
It all seems good, except for `readval` — it doesn't actually read anything (assuming that macro arguments behave like immediate operands, i.e., they don't count as a read).

Any ideas? I'd propose something like `setscriptvar`, but it seems too long.

**Comment by Rangi42** [comment]
Updated to use `setval` instead of `readval`; `readmem/writemem/loadmem` instead of `readfrom/writeto/loadto`; and refer to "buffers" instead of "memory" for the `MEM_BUFFER_*` constants that direct to `wStringBuffer*`.
