### ISSUE TITLE
Improve music macros

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#556]
PR #321 (closed for being years out of date) had some possibilities for changes to sound macros, mostly taken from pokered. In general it would be nice to have meaningful parameter values for each macro, and internally combine them into the raw bytes. Macros like `sound_duty` and `slidepitchto` already do this.

Prism also has an improved header structure. Instead of defining each channel with `musicheader`, which takes a parameter for the channel count that's only meaningful for the first one, it sets the channel count with `channelcount` and defines each channel with `channel`.

**Comment by mid-kid** [comment]
Ideas thrown around on the Discord:
- `volume`: Split into the left and right components, drop the useless hex notation, warn people about values higher than 7.
- `dutycycle`: Make `DUTY_X` constants for the different percentages, warn the user about values greater than 3.
- `stereopanning`: Unpack all the hex values into bitwise notation (`%00000000`)
- `tone`: Reduce the amount of hexadecimal characters to 3 (`$xxxx` → `$xxx`), and warn users about values bigger than 2047.
- `vibrato`: Just do this: https://github.com/pret/pokecrystal/wiki/Sound-engine-commands#e1-vibrato-byte-byte
- Actually, for a lot of commands, that document already provides good macros: `soundinput`, `intensity`, `notetype`...
- any: Use a constant for true/false arguments that have a meaning beyond a boolean expression.
- any: Warn the user if using too big values, and truncate them properly.

**Comment by mid-kid** [comment]
Just a note about stereopanning, it's only used with either `$f0` `$f` or `$ff` as arguments. If this only applies the bits relevant to the current channel, the bitwise constants would actually be useless.

**Comment by Monstarules** [comment]
@Rangi42 the macros names are fine. We could do with a few updates on the wiki though, I don't think the actual guide for the effects are written in plain enough english, though.

@mid-kid stereopanning in Pokecrystal only uses $f0 $f and $ff , but the effect that it provides (sound panning when stereo is enabled) is used in many songs for romhacks, so perhaps that wouldn't be entirely useless, although for the sake of vanilla Crystal it is.

My suggestion is to start by removing the useless things and updating the wiki. That would be removing: - `unknownmusic0xe2`
-`unknownmusic0xe7`
- `unknownmusic0xe8`
- `unknownmusic0xf9` 
My guess for what these originally were intended for were effects such as sforzando piano, ritardando, accelerando, and maybe a repeat. These musical effects though are all completely possible with the current effects and commands, and likely didn't need to be completed. TL;DR, leftover useless code (they literally only perform a single function and never act on it).

**Comment by Monstarules** [comment]
Found one more macro that doesn't do anything:
- `unknownmusic0xee`

That stores something at an address...and that's it. It's not used in any songs. Testing it, it does nothing. Absolutely nothing.

**Comment by Rangi42** [comment]
@Monstarules This is the site pokecrystal issues. It needs to exactly reproduce the original ROM, so we can't remove unused content or optimize anything. These are useful suggestions for an optimization/improvement fork like tinycrystal, though, or you could start an "optimize the music engine" tutorial on the pokecrystal wiki.

**Comment by mid-kid** [comment]
I meant that bitwise arguments are unnecessary, so there's no point in doing `%11110000` when only `$f0` is ever used at all. It'd only be useful to unpack if the four bits were actually used in a meaningful way besides "play all channels on the left speaker".

And yeah, even if some music commands are unused, as long as they're implemented, even with just a `ret`, they deserve a music command macro. We never know if spaceworld or pokegold will ever shed any light on what they might've been used for, and if so it's really useful to document.

**Comment by Rangi42** [comment]
@mid-kid @Monstarules Do you two want to collaborate on a concrete proposal for revised music commands? Since Monstarules has written some music already.

**Comment by dannye** [comment]
I don't mind doing the work for pokecrystal and pokered since both repos have some bad naming that should be addressed, and we want the repos to be as compatible as possible.
Some of my thoughts for pokered are here: [pokered #113](https://github.com/pret/pokered/issues/113)

I would like to get consistent about using underscores in music command macro names. Some commands already use underscores, like `tempo_relative`.

For pokecrystal, I suggest `pitchoffset` should be renamed to `transpose` and `tone` should be renamed to `pitch_offset`. The current names do not reflect the purpose at all.
Similarly, I think `intensity` and `soundinput` are very bad names.

Here are all my initial suggestions (totally open for criticism):
- `musicheader` -> `music_header`
- `notetype` -> `note_type`
- `pitchoffset` -> `transpose`
- `dutycycle` -> `duty_cycle`
- `intensity` -> `volume_envelope`
- `soundinput` -> `pitch_sweep`
- `sound_duty` -> `duty_cycle_pattern` (perhaps `pwm` - see [pokered #113](https://github.com/pret/pokered/issues/113))
- `togglesfx` -> `toggle_sfx`
- `slidepitchto` -> `pitch_slide`
- `togglenoise` -> `toggle_noise`
- `tone` -> `pitch_offset`
- `restartchannel` -> `restart_channel`
- `newsong` -> `new_song`
- `sfxpriorityon` -> `sfx_priority_on`
- `sfxpriorityoff` -> `sfx_priority_off`
- `stereopanning` -> `stereo_panning`
- `sfxtogglenoise` -> `sfx_toggle_noise`
- `setcondition` -> `set_condition`
- `jumpif` -> `jump_if`
- `jumpchannel` -> `jump_sound`
- `loopchannel` -> `loop_sound`
- `callchannel` -> `call_sound`
- `endchannel` -> `ret_sound`

The representation of the arguments to each macro should be re-evaluated too, and I like @mid-kid's suggestions.

Also mentioned in [pokered #113](https://github.com/pret/pokered/issues/113), `loopchannel`, `callchannel`, and `endchannel` are pretty bad. "channel" doesn't make a lot of sense. I think the simplest, most consistent alternative is replacing "channel" with "sound".
I kind of want to replace "end" with "ret" too because the `endchannel` command is used in two scenarios: 1) end the channel and 2) return from a branch called by `callchannel`.
So, sound only ends in one of the two scenarios, so "end" isn't really appropriate. I think "ret" is a little more general to cover both cases.

Thoughts?

**Comment by dannye** [comment]
> Just a note about stereopanning, it's only used with either `$f0` `$f` or `$ff` as arguments. If this only applies the bits relevant to the current channel, the bitwise constants would actually be useless.

I wanted to point out that `stereopanning` behaves differently in red and crystal.
As @mid-kid pointed out, in crystal it is only ever used with `$f0`, `$0f`, and `$ff` and the command can only affect the channel it is used on.

In red, the `stereopanning` command can be used with any 8-bit value and it affects all 4 channels regardless of which channel executes the command. This a small, annoying way where perfect compatibility is impossible.

**Comment by mid-kid** [comment]
I always thought "channel" was a fine term, since each of these scripts only control what plays on _one_ channel, and as such `loopchannel` to loop the contents of a single channel sounds just about fine. That said, `sound` is okay as well, though I'd use prefixes instead of suffixes, and consider prefixing/suffixing `jumpif` as well.

Thanks for picking this up. It's about time these macros get a revamp. Do you think some commands could have their argument lists adapted (as in, use fewer arguments and common defaults, and possibly give warnings about invalid arguments)?

**Comment by Rangi42** [comment]
I'm okay with "channel" too. Which reminds me of porting Prism's improvement to music_headers.

For example, this:

```
Music_Bicycle:
	musicheader 4, 1, Music_Bicycle_Ch1
	musicheader 1, 2, Music_Bicycle_Ch2
	musicheader 1, 3, Music_Bicycle_Ch3
	musicheader 1, 4, Music_Bicycle_Ch4
```

could be this, without the redundant `1`s:

```
Music_Bicycle:
	channel_count 4
	channel 1, Music_Bicycle_Ch1
	channel 2, Music_Bicycle_Ch2
	channel 3, Music_Bicycle_Ch3
	channel 4, Music_Bicycle_Ch4
```

And this (note how channels don't have to start at 1 or be sequential):

```
Sfx_Surf:
	musicheader 3, 5, Sfx_Surf_Ch5
	musicheader 1, 6, Sfx_Surf_Ch6
	musicheader 1, 8, Sfx_Surf_Ch8
```

could be this:

```
Sfx_Surf:
	channel_count 3
	channel 5, Sfx_Surf_Ch5
	channel 6, Sfx_Surf_Ch6
	channel 8, Sfx_Surf_Ch8
```

**Comment by dannye** [comment]
The header macro for red is even cleaner:
```
Music_PalletTown::
	audio Music_PalletTown, Ch0, Ch1, Ch2
```

And the channels also don't have to start at 1 or be sequential:
```
SFX_Cry00_1::
	audio SFX_Cry00_1, Ch4, Ch5, Ch7
```

**Comment by dannye** [comment]
@Rangi42 @mid-kid That reminds me there are two other issues I want to get input from others on before finalizing this.
In pokecrystal, the channels are numbered 1-8. This used to be the case for pokered, but a while ago I changed them to 0-7, thinking that it made more sense. But I might have done that prematurely. To make pokered and pokecrystal match, should pokered go back to 1-8 or should pokecrystal be changed to 0-7? Are there strong arguments for either case?

The other issue is that I changed pokered's notes from this:
```note A_, 1```
to this:
```A_ 1```
The `note` macro was removed and the `A_` etc. constants were changed to macros.
pokecrystal still uses the `note` macro, but pokecrystal also uses the `A_` etc. constants in other contexts like the `slidepitchto` macro so it might not be so straight forward to remove the `note` macro. For consistency should pokered just go back to `note A_, 1`?

**Comment by mid-kid** [comment]
I have no clue why they were named `1-8`, nor what the proper naming for them is. While I think `0-7`, makes more sense, the [nintendo manual](https://ia801906.us.archive.org/19/items/GameBoyProgManVer1.1/GameBoyProgManVer1.1.pdf) refers to the four _hardware_ channels as Sound 1 through 4.

As for `note`, I genuinely think it makes more sense to have a macro for this. While I know it isn't a straight "command", since it has no index in a table, it's consistent with the way we implement for example `anim_wait`, `frame`, and many of the movement macros, and imo looks better in scripts.

**Comment by dannye** [comment]
Yeah, I'm leaning towards adding the `note` macro back into pokered.

As far as channel numbers, I'm really torn. I also noticed the manual uses 1-4, so that's probably what I will go with unless someone really prefers starting with 0.

**Comment by dannye** [comment]
@Rangi42 @mid-kid If you get a chance, could you take a look at #650 and https://github.com/pret/pokered/pull/223 ?

**Comment by coltongit** [comment]
Is this PR going to be worked on anymore? Or has it been pushed into the dustbin?

**Comment by mid-kid** [comment]
It has a mostly-finished PR, just lacks a couple of requested changes.

**Comment by dannye** [comment]
Sorry, just been busy and lazy. I'll try to finish it today.
