### ISSUE TITLE
"Happiness" values in data/events/odd_eggs.asm are actually Walking Cycles.

### ISSUE THREAD

**Issue by Maesejesus** [pret/pokecrystal#589]
Not really an "issue" or something important, but messing around I've noticed that these values are the walking cycles needed for the egg to hatch, and not the base Happiness of the monster.

**Comment by mid-kid** [comment]
It's technically called "Happiness", because that's the place where the happiness is stored for any non-egg pokemon. It just takes the meaning of "walking cycles" when the mon in question is an egg.

Compare with the [battle tower mon data](https://github.com/pret/pokecrystal/blob/master/data/battle_tower/parties.asm#L4), the structure is the same, but because it isn't an egg, the happiness field actually means happiness.

**Comment by Maesejesus** [comment]
Oh, then excuse me! 
Sorry for the inconvenience; this should be ignored then.

**Comment by mid-kid** [comment]
Nah, I think it's useful to change the comments for the odd_egg data, since "walking cycles" is the more relevant description there.
