### ISSUE TITLE
docs folder has diffs to fix bugs/issues with vanilla Crystal. Consider checking these into git as .patch files?

### ISSUE THREAD

**Issue by DeeDeeG** [pret/pokecrystal#612]
### Background

Hi folks,

I'm interested in poking around the Pokémon code a bit, so I am looking at the pret repos.

I noticed this repo has a lot of diffs in the docs folder, in "[design_flaws.md](https://github.com/pret/pokecrystal/blob/master/docs/design_flaws.md)" and "[bugs_and_glitches.md](https://github.com/pret/pokecrystal/blob/master/docs/bugs_and_glitches.md)"

I thought to myself, these would be much easier to apply (with `git am` or `git apply`) if they were complete patch files.

### Proposal

Make one .patch file containing each distinct fix. Probably under one folder for design flaws patches, and another folder for bug/glitch patches.

Pros:
- Faster, easier, more reliable to apply the suggested patches
- Easier/faster to verify that the suggested patches in docs folder still apply, as the code-base gets updated over time
  - Could theoretically set up continuous integration testing, where you have git apply all of these patches, and if applying the patch errors out, then you know something went wrong. Not bulletproof, but it's something.

Cons:
- Redundant info in the repo
- Have to make sure the patch files stay in sync with the docs and vice-versa
- Higher implied reliability of the patch files, versus telling folks to patch manually. ("Make these edits manually" IMO implies that a best effort was made to provide accurate patches, but they aren't necessarily tested so YMMV. If .patch files don't work, I think people would be more inclined to report it as an issue. Maybe this is a pro, not a con?)

### Who would do it?

I volunteer to do this, if it's welcome. Wanted to know if this sounded good, where you'd prefer the .patch files go, folder structure and folder names, etc... and a chance to discuss before jumping into this.

I haven't built the project yet, so I'm very unfamiliar with the code-base, but I'm pretty comfortable around Git, so I figured this is something I could do to maybe help the project.

Best regards,

\- DeeDeeG

**Comment by aaaaaa123456789** [comment]
The patches aren't really the best possible code out there; they are the minimal patch necessary to exhibit the behavior and a possible fix. This makes it a bad idea to distribute them as "ready to apply" canned fixes.

**Comment by DeeDeeG** [comment]
Okay, thanks for the response. If this overall seems like something not worth doing, maintainers can feel free to close this issue. Wouldn't want people to blindly apply patches that don't do exactly what they're expected to do, or that might cause problems with ROM hacks they're working on, etc.

**Comment by Rangi42** [comment]
Thanks for the offer, but yeah, .patch files would not be an improvement.

The current Markdown diffs are written more for people to read and learn from, not for the codebase itself. So instead of noting the exact filename and line number with a .patch's `@@@` and `+++`, they just mention the file and routine name and give enough context to find the right part. This lets them be applied even if you've already made some changes to the project, and the line numbers have changed.

The fixes as written also make it easy to rearrange parts of long fixes, and intersperse explanation of why it's done that way, or describe alternative fixes. So a person can read and understand the fix, manually apply it with any optimizations or improvements they want, and learn about the surrounding code while doing so.

If you want to help out with pokecrystal, please check out the [code cleanup](https://github.com/pret/pokecrystal/wiki/Code-cleanup) wiki page. In particular, there are still thousands of `Unknown` labels that need meaningful names, and hard-coded $hex values that aren't identified. The [pret Discord server](https://discord.gg/6EuWgX9) has a bot in #pokecrystal that monitors progress on these labels.

**Comment by mid-kid** [comment]
I think we could definitely use a tool to at least check whether these patches can indeed be applied cleanly, and rebase patches when modifications to the respective file(s) are made. This would greatly help to reduce the workload of making sure these patches are still valid, and we could potentially use this for the wiki as well, where much bigger patches are written, which can often be a pain in the ass to verify for completeness.

Of course, such a thing would probably require a more standardized patch format to use in these documents, such that the `+++` and `@@@` lines can at least be deduced by the tool, but I think it's worth considering.

**Comment by DeeDeeG** [comment]
for a bare minimum "will git apply the patch without complaining" test, there is: [`git apply --check`](https://git-scm.com/docs/git-apply#Documentation/git-apply.txt---check)

I'm reasonably confident that could be run from Travis CI and detect issues.

For more than that, I'm not really sure.

**Comment by DeeDeeG** [comment]
For another way to set this up, rather than patch files: One could also apply each "suggested diff" as a commit (on a separate branch), and simply rebase the branch against the tip of master from time to time to check if all the commits can apply. (`git rebase` will error out if they don't, which indicates the source should be updated.)

For maintaining such a branch: The patches in said branch can be maintained/updated with `git rebase -i`. (`pick` commits that don't need updating, which is the default, and specify `edit` for commits that need updating.)

---

For checking when the source files have changed: There is `git diff -- [path1/to/files] [path2/to/some/more/files] [pathx] [pathy] [pathz]` etc.... (If the documentation pages with diffs in them are updated, one can presume there is likely an updated patch that needs validating.)

I think the main non-git-native functionality needed here would be extracting markdown code blocks with diff-like syntax (lines starting with pluses and minuses, etc...) and somehow having enough info to transform them into valid patch files. (I would lean toward doing everything natively in git where possible.)

The wiki is also a git repository, so the above applies to the wiki as well.

---

Instead of trying to extract the diff code blocks from markdown and *transform them* into valid patches, one could rewrite the markdown blocks to *be* ready-to-go, valid patch/diff files. One would then only need to copy/paste them into a text editor to be able to apply them (or to tweak, then apply, etc.)

I guess the docs and wiki could link out to patch/diff files instead of having them inline to get rid of the redundancy, and improve the ability to automatically validate them.

/brainstorming

**Comment by aaaaaa123456789** [comment]
It would be nice to check if the patches are valid, but keep in mind that not being able to apply them automatically is a feature, not a bug.

**Comment by mid-kid** [comment]
If we want to check and (re)-generate their context they will need to be applicable automatically somehow. Of course, we don't need to mention how the user can do that themselves in the document, or encourage it in any other way, but it is of no use to try to hide it behind a "maintainer-only" fork or anything.

**Comment by DeeDeeG** [comment]
Another idea for validating the patches: Assuming the main ROM produced by this repo has a stable md5sum (it appears to?), and assuming the ROM with all patches applied builds (unclear if this would actually build right now?) and produces a stable md5sum, one could have a script to apply all the patch files and check the md5sum of the fully-patched ROM against its intended, known-good md5sum.

If this is part of CI, it would be pretty easy to catch which commit was the culprit for desyncing the "example diffs" from the main code. Also: I wonder if there's a way to have CI surface "warnings" or info alerts, instead of actually failing? Because I assume updating the main code is more important than keeping the example diffs up to date.

For a lighter touch, and no automation: Each assembly file could have a comment listing documentation/wiki pages that have diffs against that file, and a comment saying "when updating this file, please check whether the diff described at [URL] would fail to apply to this file as updated."

**Comment by DeeDeeG** [comment]
Hi again folks, 

I discussed this on Discord, but my idea is a bit more polished now.

The general idea here would be to create .patch files in the `git diff` format for every bug fix described in the docs or the wiki.

See this branch at my fork for two example patches: https://github.com/DeeDeeG/pokecrystal/tree/patches/patches/bugs_and_glitches _(These DO apply cleanly. Where possible, I used the exact same lines of "context code" around changes as the diffs in the docs themselves used.)_

It's possible to then run `git apply --check` to see if the patches apply cleanly. For more advanced patching logic, we can try the [`--3way`](https://git-scm.com/docs/git-apply#Documentation/git-apply.txt---3way) flag to attempt a three-way merge of the patch contents, the version of the file(s) it was made against, and the current state of the file(s) it patches. We may also want to use [`--reject`](https://git-scm.com/docs/git-apply#Documentation/git-apply.txt---reject) to highlight which portions of the patch no-longer apply, e.g. in the CI logs.

It would also be possible to build actual ROMs out of the master branch, with patches applied. These ROMs should be made with the smallest number of separate "patch sets" that don't conflict with one-another. If it yields a small number of ROMs, patches could be grouped to be thematically related, and one could produce ROMs with those "patch groups." Building the ROMs allows checking their SHA1s are stable over time, and ensures that the patched source code still compiles properly.

Not much of this is really new compared to the discussion in Discord, but I think this updated proposal is at least feasible now.

What's new is:

- I found a way to actually convert every patch in the docs or wiki into working patches. But this is a manual process, and it's a bit slow/tedious.
- Producing multiple, non-overlapping ROMs with more than one patch per ROM brings "building" all the patches closer to a reasonable number of builds.
- I'm pretty sure I know the commands to make CI validate the patches. (there are a couple of options, but any of them seem good IMO).

My questions are:

- Is this more thought-out proposal something folks would want done?
- Discussion around details for implementing this
  - Since it would make every CI run a lot heavier, consider moving this to its own branch, or a fork, just to keep the existing CI config light, simple and fast.

**Comment by mid-kid** [comment]
Frankly, putting together a comfortable "patchset description format" as well as making it possible to not only extract the diffs from the markdown files but also re-insert automatically reconstructed versions of them makes this entire thing a little too complex to my tastes, and something rather hard to get "just right™", and would probably make it harder to contribute.

The problem with having to make "patchsets" is making sure they don't conflict as things are added and changed, and dealing with patches that can only be applied in a certain order. I don't see this not getting messy. Not to mention comparing a SHAsum is rather counterproductive when the contents of these files are meant to change regularly (and as such would change the SHAsum, rendering it useless).

I've kind of given up on this idea, since the only thing I see as workable is just making sure the patches apply (regardless of whether they build properly) and re-generating the context lines to match the current code. And, while this would be nice, it seems like a bit too much work to get working for little gain. There's bigger fish to fry, like making proper API docs.

If you really want to carry on with this, I suggest starting with something that does what I said above: extract patches from a file, try to apply them, if they don't match exactly, try to apply them with that --3way option and re-insert them into the file. You can look into the "patchset" thing when that's done. Small steps.

**Comment by aaaaaa123456789** [comment]
The issue with these patches hasn't changed: they are _sample code_, not canned fixes that should be blindly applied to a release ROM.

**Any idea involving collecting patches into a ROM should be immediately rejected.** It doesn't even matter if you can apply all the patches into a ROM — we know you can't, and trying to separate the patches into non-overlapping subsets requires a lot of manual work and maintenance _for no gain whatsoever_. The "resulting set of patches", so to speak, is completely meaningless.

If you can build a mechanism to check if _individual_ patches remain valid (i.e., they don't contain errors and they can be applied), go ahead. While focusing on using `git` for a task that is completely unrelated to version control seems awkward at best, if it works, go ahead — [build a bike shed and paint it whatever color you want](https://shed.bike).

But this is ultimately a documentation validation tool, and it should remain constrained to that scope and that scope alone. Focusing on generating ROMs opens the door for heavy misuse (e.g., by treating the patched ROMs as good reference bases) while encumbering the actual process of documenting patches. Validating hashes is particularly evil in this regard — it prevents people from easily updating the documented patches (since they'd have to compute a new resulting set of patches, apply it, find the new SHA-1 for the patched ROM and update the CI scripts), and it checks for a situation that doesn't matter (whether the patched ROM stays identical — it's not a reference ROM).

**Comment by DeeDeeG** [comment]
I'm not talented at programming, so I would just be doing most of this stuff (writing the patches, checking them against the docs/wiki) manually. It can then be run on CI "to the extent it works" and "as needed" to make reviewing the docs "partly automated." :tm:

Anything beyond that is out of the scope of my abilities and out of scope of my plans. I don't disagree with your approach on this, but I can't really implement it.

And not being talented at programming makes it hard to contribute in other areas, I think. Unless there's a lot of stuff like #614  where the info is already there, without having to understand the code?

**Comment by aaaaaa123456789** [comment]
The C in CI stands for _continuous_. Doing it manually defeats the point — if we want to validate the patches once, we can just check them manually, which is certainly less work than manually compiling `.patch` files, adding the necessary metadata (line numbers, etc.), figuring out how to coerce `git` into checking them, and so on.

If there is no setup to automate this task, there's no improvement.

**Comment by DeeDeeG** [comment]
Line numbers are added _automatically_ by `git diff`.

If you can verify that a patch applies, you can apply it.

If you apply a patch and run `git diff`, you get a patch _for the cost of one command on the command-line_.

**Comment by aaaaaa123456789** [comment]
And who's going to generate that patched version for `git diff` to consume in the first place? The patches in the documentation don't come from diffing anything; they are mostly handwritten.

You say you'll do it, but what about when the docs change? Now we have two patches to maintain, because there's no automation. It's additional cost for little gain.

**Comment by DeeDeeG** [comment]
You don't need to maintain the patches, the patches are an incremental improvement over no automation. That's why I keep mentioning they could go in a non-default branch, or a fork, to hide them from easily-confused newcomers.

If a single patch gets out-of-date, update that single patch. then you're back to having _the whole set of patches_ verified, rather than having to guess, or catch everything as it comes in.

This would be an improved workflow for me in particular. If it doesn't generalize for everybody, I'm not trying to force it on anyone.

(You get pretty strong guarantees that the patches all still work from my proposal. The cost is maintaining patches manually, barring some automated tool per @mid-kid's suggestion.)

I've already described what this is supposed to accomplish. I've already said no-one needs to do it, but I happen to want to. I don't really want to defend this proposal to someone who already doesn't want it. We aren't building toward anything here.
