### ISSUE TITLE
Handling battle scenario with zero pokemons

### ISSUE THREAD

**Issue by joneslee85** [pret/pokecrystal#634]
An [edge case where people use cheat to bypass the pokemon selection](https://www.youtube.com/watch?v=Z1b0Vk8Wnto) then get into glitches when get into battle.

Wondering if you think it is a good idea to guard against such scenario.

**Comment by Pokechu22** [comment]
I don't think it makes sense to guard against things like that, at least in the sense of patching things to prevent cheats... since cheats can undo such patches, so if someone _wants_ to get that glitchy behavior, they can force it.

Of course, for romhacks that might put you into such situations intentionally without wanting glitchy behavior, it might make sense to guard in some way.  Pokémon Yellow has the unused [Hurry, get away](https://www.youtube.com/watch?v=m2EVWpfLSQg) battle mode (which seems to be intended for that purpose), but I don't know if something like that exists in crystal.

**Comment by ketsuban** [comment]
I was under the impression that [as a Gen 2 game Crystal already has protections against getting into battles with zero Pokemon](https://tcrf.net/Pokémon_Gold_and_Silver#Battle_Ends_Automatically).

**Comment by mid-kid** [comment]
This repository contains the _unmodified_ code for the Pokémon Crystal game. As such, it isn't up to us to fix such game design issues. It's up to whoever decides to hack this game.
Thankfully, like @ketsuban mentioned, there's already some basic protections in place in the original game, as you'll automatically win any battle if you have no Pokémon in your party.
