### ISSUE TITLE
Constants that could have prefixes

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#698]
- ~~`MON_`~~: Pokémon have unique names, so they're not ambiguous and there are no collisions.
- [ ] `TYPE_`: thus `TYPE_PSYCHIC` instead of `PSYCHIC` (easily confused with the trainer class `PSYCHIC_T`).
- [ ] `ENV_`: thus `ENV_TOWN` instead of `TOWN`. Environment names are generic words and this is a short prefix.
- [ ] `ITEM_`: thus `ITEM_BLACKBELT` instead of `BLACKBELT` (can be confused with the trainer class `BLACKBELT_T`).
- [ ] `TRAINER_` or `TC_`: thus `TRAINER_BLACKBELT` or `TC_BLACKBELT` instead of `BLACKBELT_T`. (Changing them to {`ITEM_BLACKBELT`, `BLACKBELT`} instead of {`BLACKBELT`, `BLACKBELT_T`} would be too confusing, but a `_T` suffix without an actual name collision would be odd.) Con: `trainer` script declarations would be even longer with a `TRAINER_` prefix (which `TC_` solves).
- [ ] `MOVE_`: thus `MOVE_SPARK` instead of `SPARK`. (This bit me once when adding a trainer for Spark.)

**Comment by aaaaaa123456789** [comment]
I'd strongly argue against this. Keeping the constants short is great, and there's very few collisions. I'd argue in favour of adding a single-letter suffix to colliding constants instead, thus removing the usual problem of using the wrong constant (since the unsuffixed constant wouldn't be defined at all) while not cluttering the entire codebase due to a handful of outliers.

**Comment by Rangi42** [comment]
That's a valid perspective. Consistent prefixes might be the way to go for a fresh project, like pokegold-spaceworld does, but the current constants are fine except for a few cases.

- `BLACKBELT_T` is the trainer class, `BLACKBELT` is the item: change that to `BLACKBELT_I`
- `PSYCHIC_M` is the move, `PSYCHIC_T` is the trainer class, `PSYCHIC_T` is the trainer class, `PSYCHIC` is the type: change that to... `PSYCHIC_TYPE`?

**Comment by aaaaaa123456789** [comment]
I wouldn't oppose to `PSYCHIC_TC` and `PSYCHIC_TY` to avoid any confusion.

**Comment by Rangi42** [comment]
I'd find `PSYCHIC_TR` more obvious than `PSYCHIC_TC`, especially paired with `PSYCHIC_TY`, but something along those lines is fine.

**Comment by mid-kid** [comment]
The problem is not only the constants that are already defined, but the constants that a user may add for trainers, items or moves, which can and have been colliding on several occasions.
Add this to the readability factor of certain macros (for example `map` where `ENV_` would be useful to know what `TOWN` means, and script commands like `setval`), and I honestly think it's a better idea to prefix everything than mess with this on a case-by-case basis, which is _sure_ to bite many people in the ass.
Specific exceptions _aren't_ easy to remember, and I've hit this problem before with tools written around this codebase, which have to hardcode these specific exceptions.

As for what is being discussed above, I don't really think it's worth figuring out these specific exceptions further than they already are. Most of these have a clear "main" constant that will be used 90% of the time (looking at `CURSE` and `TOWN_MAP`), and it's not going to make it much clearer when a user forgets the suffix.

**Comment by Rangi42** [comment]
How about `TOWN_MAP_POSTER` for `TOWN_MAP_D`, and `UNKNOWN_TYPE` or `QUESTION_TYPE` for `CURSE_T`? You're right that the item `TOWN_MAP` and move `CURSE` are more common, but these names would be more descriptive for the less common ones than single-letter suffixes.

**Comment by mid-kid** [comment]
`CURSE_TYPE`
the rest is fine

**Comment by Rangi42** [comment]
#699 added a few suffixes to the ambiguous constants like `BLACKBELT` and `PSYCHIC`.
