### ISSUE TITLE
Link party in WRAM is mislabelled

### ISSUE THREAD

**Issue by aaaaaa123456789** [pret/pokecrystal#733]
`wLinkPlayerData` is two bytes off, since the game actually transfers the player ID before the party. (This makes no difference to the disassembly because those labels are completely unused — the game reads sequentially from `wLinkData`.)

**Comment by aaaaaa123456789** [comment]
While we're at it, `ld b, PARTY_LENGTH` in `engine/link/link.asm` at lines 635 and 801 should just be `ld b, 6`. The fact that the game sends six bytes of preamble is not related to the party length.

**Comment by Rangi42** [comment]
It looks to me like `Link_PrepPartyData_Gen2` copies these bytes to `wLinkData`/`$c800`:

- 6 repeating the `SERIAL_PREAMBLE_BYTE`
- 11 (`NAME_LENGTH`) for `wPlayerName`
- 1 for `wPartyCount`
- 6 for `wPartySpecies`
- 1 for `wPartyEnd`
- 2 for `wPlayerID`
- and then the `party_struct`s

That would mean `wLinkPlayerData` starts at `$c81b`, not its current `$c813`; it's 8 bytes off.

(However, `Gen2ToGen1LinkComms` copies the player name, party count, and party into `wLinkPlayerName + wLinkPartyCount + wLinkPartySpecies + wLinkPartyEnd`, which also start at `$c800` and look unrelated to the similar data that's part of `wLinkData` starting after the preamble. Correct?)

Anyway, since the `wLinkPlayerData` labels are all unreferenced, I'd rather just delete them until/unless we can correctly label the contents of the raw `wLinkData` `NEXTU`.

**Comment by Rangi42** [comment]
For now `SERIAL_PREAMBLE_LENGTH EQU 6` is independent of `PARTY_LENGTH`.

**Comment by Rangi42** [comment]
This will probably get resolved along with https://github.com/pret/pokegold/issues/67.
