### ISSUE TITLE
Bug: PRZ and BRN stat debuffs are not always applied to enemy mon when switching

### ISSUE THREAD

**Issue by landesherr** [pret/pokecrystal#746]
Found a peculiar behavior of the battle engine while testing a ROM hack that features more aggressive AI switching that, as far as I can tell, applies to the base game:

### Problem Statement
Under certain conditions, an enemy mon can be paralyzed without the 3/4 reduction to speed, or burned without the 1/2 reduction to attack

### Scenario
1. An enemy trainer's mon is paralyzed or burned
1. The enemy trainer AI switches that mon out for another
1. The new mon that has been switched in faints
1. The AI selects the mon with PRZ/BRN as its next choice
1. The mon with PRZ/BRN now has its full speed or attack
*Note that this bug oddly does not apply if the enemy trainer AI switches the PRZ/BRN mon in when its current mon has not fainted*

### Investigation
The logic to apply the debuffs based on PRZ and BRN status effects is the function `ApplyStatusEffectOnEnemyStats` in `engine/battle/core.asm`. I attached a debugger to the game, setting a breakpoint on the address of this function. I found that it *did not* break when switching in a paralyzed or burned mon after a faint, but *did* during an AI switch.

### Remedy
`ApplyStatusEffectOnEnemyStats` is only ever called from the `InitEnemyMon` function. I hypothesized that this pathway is only conditionally taken, and this bug could be fixed by moving the call to somewhere that is unconditionally called whenever an enemy mon is thrown out. I made the somewhat inelegant change of moving the call to `ApplyStatusEffectOnEnemyStats` to the `Function_SetEnemyMonAndSendOutAnimation` function, after which I attached my debugger and reproduced the scenario, observing that the enemy stat debuffs applied under all switch-in/switch-out conditions.
**Related Commit**: https://github.com/peterjtalen/Pokemon_Super_Crystal/commit/e2e199a61e334bd82dbf5903bc8f86e03ad8cfbd

**Comment by aaaaaa123456789** [comment]
The goal of this repository is to exactly replicate the ROMs that were distributed by Game Freak. Did you perhaps intend to make a documentation fix?

**Comment by Rangi42** [comment]
I assume they mean to document this fix, yes.

This does sound like a bug/oversight, since the status condition debuff *is* applied for some switch-ins but not others.

**Comment by landesherr** [comment]
Yes, sorry for the lack of clarity on that point. My intent was to document the bug and the fix for it.

**Comment by Rangi42** [comment]
It reminds me of the "[Perish Song and Spikes can leave a Pokémon with 0 HP and not faint](https://github.com/pret/pokecrystal/blob/master/docs/bugs_and_glitches.md#perish-song-and-spikes-can-leave-a-pok%C3%A9mon-with-0-hp-and-not-faint)" glitch, since switching back out after a faint has different handling than the usual+correct case.

**Comment by peterjtalen** [comment]
This bug is not listed on the list of documented glitches/bugs for gen 2 on bulbapedia: https://bulbapedia.bulbagarden.net/wiki/List_of_glitches_in_Generation_II

and also not listed on pokecrystal's list of known bugs.

It's weird that no one ever noticed this bug, but the enemy AI switches out pokemon so rarely that conceivable the only really reliable way to have encountered this bug in vanilla Crystal would be to PRZ/BRN the opponent and then roar/whirlwind them. Landesherr's improvements to the AI in our hack is what uncovered this.

**Comment by Rangi42** [comment]
Two things to ensure before documenting this bug:

1. Does it affect link battles too? `InitEnemyMon` and `Function_SetEnemyMonAndSendOutAnimation` *are* called in link battles, but I'd expect a switch-related bug to have been noticed sooner in them.
2. Does the fix break anything? In particular, if an enemy mon already has PRZ/BRN when the battle starts, would this fix prevent the stat drop? If so, we can't just leave both `ApplyStatusEffectOnEnemyStats` calls in, since that would change this bug from no drop to a double drop.

**Comment by Rangi42** [comment]
("Fix: Edit TruncateHL_BC..." is missing an ending colon.)

**Comment by coltongit** [comment]
> ("Fix: Edit TruncateHL_BC..." is missing an ending colon.)

Fixed in #960
