### ISSUE TITLE
Clear function and other MACROS

### ISSUE THREAD

**Issue by aljohnston112** [pret/pokecrystal#779]
If you run the following regex on the whole project, you get 2258 matching lines. 

\s\*xor\ (.)\s\*ld\ \[\S\*\], \1

It catches lines like the following.

xor a
ld [wMusicPlaying], a

Could a function be made for these types of lines? Something like the following.

clear: MACRO
	xor \1
	ld \2 \1
ENDM

Then you can run the above using the following.

clear a,  [wMusicPlaying]

I can not find any example of something like this in the project. Is that because MACROs can't be exported or imported? audio/engine.asm has about 50 usages, and if enough of these types of MACROs were made, it could help make the code more readable.

Am I missing something?

**Comment by aaaaaa123456789** [comment]
What you propose would be quite meaningless because `a` is a required operand for both instructions. But let's amend your proposal a bit to this:

```
clear: MACRO
  xor a
  ld [\1], a
```

This would still be **a very bad idea**. The reason is that it obscures what's going on for no good reason. Those two lines are very idiomatic and everyone who has a little experience with assembly knows what's going on. On the other hand, a `clear` macro would obscure the code with zero benefits.

The reason why these pseudo-ops don't exist is because they are generally bad, not because they can't be made. The few that do (like `farcall`) have very good reasons to exist; making pseudo-ops just because it's possible leads to madness (and completely unreadable code).

**Comment by aljohnston112** [comment]
clear is a bad name, but what if the name was non obscure? clear is an example of a small change, but what if there are larger blocks that could be condensed?

**Comment by aaaaaa123456789** [comment]
It's not the name what is obscure, but the concept. There's a million projects that attempt to create macros for common sequences like this one, and there's a good reason why experienced assembly programmers never use any of those projects.

**Comment by aljohnston112** [comment]
Forgive me if I'm being ignorant, but don't compilers generate code from "macros" for common sequences?

**Comment by aaaaaa123456789** [comment]
That's pretty much how compilation works, yes, but the whole point of assembly is to have full control of the generated binary. Macros aren't optimizable like compiled code is, also. For instance, invoking that macro twice would have an excess `xor a`; a compiler would (hopefully) optimize that out, but since this is raw assembly, there's no optimizations other than the ones you write.

**Comment by aljohnston112** [comment]
You mean like this?

	xor a
	ld [hli], a ; rNR50 ; volume/vin
	ld [hli], a ; rNR51 ; sfx channels

You could pass the number of times to `ld [hli]` into the MACRO, but then you would need somewhere to store and decrement and it would not be worth it. 

Couldn't rgbasm perform optimizations?

**Comment by aaaaaa123456789** [comment]
At that point you'd just be creating a programming language.

**Comment by Rangi42** [comment]
Such a macro would tempt people to write:

```
    clear wFoo
    clear wBar
```

Which would expand to sub-optimal code:

```
    xor a
    ld [wFoo], a
    xor a ; this is pointless
    ld [wBar], a
```

In general you want to avoid macros that hide the actual code, because when writing low-level assembly language for a constrained platform like the Game Boy (where you don't have gigabytes and gigahertz to spare), you want to know how adjacent code can interact, and know just what it's doing.

There are a number of examples of optimizing short pieces of code to do certain things: https://github.com/pret/pokecrystal/wiki/Optimizing-assembly-code Personally I'd be comfortable with macros for some of those, where (a) the macro would save typing many lines of code (not just two), and (b) the code is non-intuitive unless you're very used to seeing the whole pattern at once. For example:

```
add_a: MACRO
; \1: hl, bc, or de
	add LOW(\1)
	ld LOW(\1), a
	adc HIGH(\1)
	sub LOW(\1)
	ld HIGH(\1), a
ENDM

    ; a = SomeListOfBytes[12]
    ld hl, SomeListOfBytes
    ld a, 12
    add_a hl
    ld a, [hl]
```

However, even this is probably not worth doing; just learn the five-line pattern and you'll be able to write it and to recognize it when reading other code.
