### ISSUE TITLE
Move the non-Pokémon icon graphics

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#987]
- [ ] gfx/icons/item.png -> gfx/stats/item.png
- [ ] gfx/icons/mail.png -> gfx/stats/mail.png
- [ ] gfx/icons/mail_big.png -> gfx/naming_screen/mail.png

**Comment by vulcandth** [comment]
Although I agree with `mail_big.png` should be moved (since it is being used by naming_screen code).. I'm not as sure about the first two.
`item.png` and `mail.png` are lumped in and used by the rest of the mon_icon code, and I think for the purposes of the disassembly they probably should remain.

Just providing a counter-argument.. i'm not firm in saying that we can't move them. I'm sure you have other reasoning.

**Comment by Rangi42** [comment]
I thought about making a gfx/party directory just for them, but we already use gfx/stats for the party pal files, and that's where you access the stats screen from, so I think it makes sense.

The icon graphics are used in the party menu, but also in the overworld. Especially when people expand that to use a unique icon per species, I think it's easy for the item and mail files to get lost/forgotten. And with them separate, it's easier to do batch operations on every png in the gfx/icons directory.

**Comment by vulcandth** [comment]
It seems like the main desire to move them is to ease romhacking, which I understand. You *could* put them in a subdirectory.. but I don't think I like that idea since there isn't a precedent for subdirectories that I can tell In the gfx/ folder. I don't have a good alternative suggestion.. so I suppose if you feel there is a benefit to moving them, I'm fine with them going in the stats folder. They are "INCLUDE"d near the code that uses them anyways, so it's not like it'll be a big deal wherever they exist.
